// Auto-generated by scripts/provision-rb2b-board.ts. Re-run to refresh.
export const RB2B_BOARD_ID = 5028658425

export const RB2B_COLUMNS = {
  "email": "email_mm3hppkk",
  "linkedin": "link_mm3hmb5c",
  "title": "text_mm3hezqd",
  "company": "text_mm3h238r",
  "website": "link_mm3hrczj",
  "industry": "text_mm3h2at",
  "employees": "numeric_mm3h3qra",
  "revenue": "text_mm3h2cv5",
  "location": "text_mm3htyer",
  "pagesViewed": "long_text_mm3h39rz",
  "intent": "color_mm3h4gp5",
  "lastSeen": "date_mm3h2619",
  "repeatVisitor": "boolean_mm3hnbts",
  "referrer": "link_mm3hk4v8",
  "rb2bTags": "text_mm3h2e6g"
} as const

export type Rb2bColumnKey = keyof typeof RB2B_COLUMNS
