/**
 * Idempotently create RB2B columns on the "Website Leads" monday board
 * (https://fruitionservices.monday.com/boards/5028658425) and write the
 * resulting column ids to src/lib/rb2bColumns.ts so the webhook handler
 * can reference them by key.
 *
 * Run:
 *   npx tsx scripts/provision-rb2b-board.ts
 */

import dotenv from "dotenv"
import { writeFileSync } from "node:fs"
import { join } from "node:path"

dotenv.config({ path: ".env.local" })

import { createColumn, listBoardColumns } from "../src/lib/mondayClient"

const BOARD_ID = 5028658425

interface ColumnSpec {
  key: string
  title: string
  type: string
  defaults?: Record<string, unknown>
}

const SPECS: ColumnSpec[] = [
  { key: "email", title: "Email", type: "email" },
  { key: "linkedin", title: "LinkedIn", type: "link" },
  { key: "title", title: "Title", type: "text" },
  { key: "company", title: "Company", type: "text" },
  { key: "website", title: "Website", type: "link" },
  { key: "industry", title: "Industry", type: "text" },
  { key: "employees", title: "Employees", type: "numbers" },
  { key: "revenue", title: "Revenue", type: "text" },
  { key: "location", title: "Location", type: "text" },
  { key: "pagesViewed", title: "Pages Viewed", type: "long_text" },
  {
    key: "intent",
    title: "Intent",
    type: "status",
    defaults: {
      labels: { "0": "Low", "1": "Medium", "2": "High" },
      labels_colors: {
        "0": { color: "#9aadbd", border: "#9aadbd", var_name: "winter" },
        "1": { color: "#fdab3d", border: "#fdab3d", var_name: "orange" },
        "2": { color: "#00c875", border: "#00c875", var_name: "grass-green" },
      },
    },
  },
  { key: "lastSeen", title: "Last Seen", type: "date" },
  { key: "repeatVisitor", title: "Repeat Visitor", type: "checkbox" },
  { key: "referrer", title: "Referrer", type: "link" },
  { key: "rb2bTags", title: "RB2B Tags", type: "text" },
]

async function main() {
  if (!process.env.MONDAY_API_TOKEN) {
    console.error("MONDAY_API_TOKEN missing in .env.local")
    process.exit(1)
  }

  const existing = await listBoardColumns(BOARD_ID)
  const byTitle = new Map(existing.map((c) => [c.title.toLowerCase(), c]))

  const resolved: Record<string, string> = {}

  for (const spec of SPECS) {
    const hit = byTitle.get(spec.title.toLowerCase())
    if (hit) {
      console.log(`= ${spec.title.padEnd(18)} → ${hit.id} (exists, type=${hit.type})`)
      resolved[spec.key] = hit.id
      continue
    }
    const id = await createColumn(BOARD_ID, spec.title, spec.type, spec.defaults)
    console.log(`+ ${spec.title.padEnd(18)} → ${id} (created, type=${spec.type})`)
    resolved[spec.key] = id
  }

  const outPath = join(process.cwd(), "src/lib/rb2bColumns.ts")
  const content = `// Auto-generated by scripts/provision-rb2b-board.ts. Re-run to refresh.
export const RB2B_BOARD_ID = ${BOARD_ID}

export const RB2B_COLUMNS = ${JSON.stringify(resolved, null, 2)} as const

export type Rb2bColumnKey = keyof typeof RB2B_COLUMNS
`
  writeFileSync(outPath, content)
  console.log(`\nwrote ${outPath}`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
