import { chromium } from 'playwright'
const browser = await chromium.launch()
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 })
const page = await ctx.newPage()
await page.goto('http://localhost:3001/about-us', { waitUntil: 'networkidle', timeout: 60000 })
await page.waitForTimeout(800)
await page.screenshot({ path: '/tmp/about-us-full.png', fullPage: true })
await page.screenshot({ path: '/tmp/about-us-fold.png', fullPage: false })
await browser.close()
console.log('done')
